CREATE TABLE users(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
Name VARCHAR(255) UNIQUE,
Password VARCHAR(255)
);

CREATE TABLE tweets 
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
p_text VARCHAR(255),
User_ID INTEGER,
Pubulished_at INTEGER
};
