CREATE TABLE users(

id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
name VARCHAR(255),
age INTEGER,
password VARCHAR(255)
birth_day INTEGER
);

CREATE TABLE tweets(

id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
user_id INTEGER REFERENCES users(id),
text VARCHAR(256)
tweet_time INTEGER,
tweet INTEGER
};

CREATIOM TANBLE 
