CREATE TABLE users(

id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(32),
age INTEGER,
birth_day INTEGER
);

CREATE TABLE tweets(

id INTEGER PRIMARY KEY AUTOINCREMENT
user_id INTEGER REFERENCES users(id),
tweet_time INTEGER,
tweet INTEGER
};

